import { describe, it, expect } from "vitest";
import { generate } from "../lib/pipeline";

// These tests describe how the pipeline SHOULD behave once fixed.
// They fail against the shipped code. Make them pass — do not edit this file
// (the grader checks it is unmodified).

describe("Bug 1 — a failed hand-off must surface as an error", () => {
  it("returns status 'error' when advanceToNextStage rejects", async () => {
    const res = await generate({
      behavior: "ok",
      advanceToNextStage: async () => {
        throw new Error("next stage unreachable");
      },
      reviewPasses: () => true,
    });
    expect(res.status).toBe("error");
  });
});

describe("Bug 2 — a truncated stream must be recovered", () => {
  it("succeeds when the first stream is truncated but a retry returns full content", async () => {
    const res = await generate({
      behavior: "truncate-once",
      advanceToNextStage: async () => {
        /* hand-off succeeds */
      },
      reviewPasses: () => true,
    });
    expect(res.status).toBe("ok");
  });
});

describe("Bug 3 — transient errors are retried and the revision loop is bounded", () => {
  it("retries through two rate-limit errors and ultimately succeeds", async () => {
    const res = await generate({
      behavior: "transient-429-twice",
      advanceToNextStage: async () => {
        /* hand-off succeeds */
      },
      reviewPasses: () => true,
    });
    expect(res.status).toBe("ok");
  });

  it("stops the revision loop and reports an error when review never passes", async () => {
    const res = await generate({
      behavior: "ok",
      advanceToNextStage: async () => {
        /* hand-off succeeds */
      },
      reviewPasses: () => false,
    });
    expect(res.status).toBe("error");
    expect(res.attempts).toBeLessThanOrEqual(3);
  });
});
